site_name: "hashitakuの日記"
plugins:
  glightbox:
theme:
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
  font:
    text:
    code: Inconsolata
  logo:
  favicon:
  name: material
  palette:
    - scheme: slate
      primary: black
extra:
  generator: false
markdown_extensions:
  - admonition:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
