name: Deploy

on:
  push:

env:
  THEME_NAME: adrenaline

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: install dep
        working-directory: quartz
        run: npm install

      - name: fetch quartz theme
        run: curl -sS https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- $THEME_NAME

      - name: build
        working-directory: quartz
        run: npx quartz build

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy quartz/public --project-name=pages
